{
  "title":"How to Build a Parabolic Powerful Solar Stove for Cooking",
  "url":"https://www.wikihow.com/Build-a-Parabolic-Powerful-Solar-Stove-for-Cooking",
  "category_hierarchy":[
    "Food and Entertaining",
    "Cooking Equipment",
    "Cookware",
    "Cookware Hacks"
  ],
  "steps":[
    {
      "headline":"Transportable in a regular station wagon car, or on the rooftop of any car, can be mounted in 15 minutes, and on the cooking support there can be placed any light metal sheet oven of half a meter deep, half a meter wide and half a meter tall, in which can be cooked 3 large pizzas together, or a water boiler of 30 liter (bunch of soup or stew) or a half a meter diameter pan (omelets and fried potatoes for a small army).",
      "description":""
    },
    {
      "headline":"Obtain need a sheet of plywood 10 mm thick 3 meters (9.8 ft) long and 1.6 meters (5.2 ft) wide.",
      "description":""
    },
    {
      "headline":"Determine on a side the exact center,",
      "description":""
    },
    {
      "headline":"Screw in next to the edge a wood screw to it's half,",
      "description":""
    },
    {
      "headline":"Take a wire or similar and tie it to the screw, than stretch it to the opposite end of the plywood, and 10 centimeters (3.9 in) before it reaches the edge tie in a pencil.Now you have the compass, rotate the compass to reach the edge where the screw is bolted in, so you draw your parabola form, cut on the curved line with a saw or a powered pendulum saw and separate the 2 wood pieces.",
      "description":""
    },
    {
      "headline":"For the outer circle: Glue the straight edge on a piece of wide lumber or plywood to have it stand with the top of the circle up, than you need to make it like a half pipe ditch all along the circular surface, than take iron wire, better if plastic coated, 2 mm thickness, and apply it in the ditch to form it in wire circle arcs., you need some 30 of them.",
      "description":""
    },
    {
      "headline":"Draw a 2.4 meters (7.9 ft) circle on the ground, and all around it each 20 centimeters (7.9 in) place a nail to complete the circle, than take wire arches you prepared and put each arch across the center to unite two nails, until you covered all the circle and all the arches are overlapped on top.",
      "description":""
    },
    {
      "headline":"Tie the arches together like this: take a wire and close to the top start passing the wire below an arch, above the next to it, below the third one, above the fourth, and so on until you meet the beginning of your wire, and tie them together, than at 5 centimeters (2.0 in) distance outer, tie them again, where the first wire was passing above, pass this one below, and where it was passing below, pass it above.",
      "description":"Keep doing that each 5 centimeters (2.0 in) away from each round until the half sphere is completed to the ground."
    },
    {
      "headline":"Take away the nails and tie the tips of the arches around the last wire ring.",
      "description":""
    },
    {
      "headline":"Take a pipe diameter 80 mm or so, wall thickness 2 mm or more,  cut two pieces of 150 mm each, put them at the end of a 2500 mm long pipe diameter 75 mm and pass them through the sphere in between the last circle at the ground level and the one previous, tie it well with wires that you will connect tying them hard to various knots on the sphere in the area, the pipes must go out of the sphere 100 mm and in the sphere 50 mm, if you can weld them to the wires is better.",
      "description":""
    },
    {
      "headline":"Where all the arches overlap, inside the smaller circle tie, cut all the arches in the center than tie them so the smallest circle for good",
      "description":""
    },
    {
      "headline":"Take newspapers, large quantity, and acrylic glue (vinyl) for wood, or better oralite (urea) based glue (the additive they put in the asphalt to harden it on the roads) since is waterproof.",
      "description":"Soak newspapers in the glue you choose to use without ruining them, than stretch them on the outer side of the parabola, until it's all covered, let it dry a day, than rotate it outside down and do the same inside, repeat outer and inner layers until you have some 10 layers total. reinforce the pipes area well. Allow to dry a few days"
    },
    {
      "headline":"Check with the wood jugs out and in for perfection, and use car quality putty or fiberglass resin to fill the gaps until the surface is smooth semi-spherical.",
      "description":"Impermeable the whole thing by painting it with waterproof paint."
    },
    {
      "headline":"Remember the 2 meters (6.6 ft) long pipe you used at point 7 to put in line the pipes in the sphere wall?",
      "description":"Cut it in two, and in between the two parts weld a L iron based frame 30 X 30 CM or larger, on which you will place the cooking pot, or the lava stone sheet to grill upon, etc, this is your stove surface."
    },
    {
      "headline":"Buy self sticking rolled mirror, cut it in stripes of 2 centimeter (0.8 in) wide, perfectly parallel using a sharp cutter and a metal ruler, starting from the center to the edge put a stripe, than 180 degrees put in continuation a second stripe, than ASIDE put another stripe from edge to edge passing near the center, same on the other side, and so on until the whole sphere is covered, make sure no air bubbles are left.",
      "description":"This should do for reflecting a lot of sun."
    },
    {
      "headline":"Build the stand you need a rotating plate, teh most common one for free or almost is a rear wheel from any car at the junk yard, take it all, brakes disk and caliper included, it will help you to keep the stove blocked using the old parking brake system.",
      "description":"Make a support of 3 regular legs to bolt it beneath and another small support (the center of a rim that fits) to make the upper center to which you weld two pipes of 500 mm diameter 60 mm wall thickness 5 mm with their center on opposite sides and parallel among them."
    },
    {
      "headline":"The structure is nothing more than 4 quarter circle arches of 70 mm pipe thin wall (1,5 mm or 2 mm) you stick on the rim welded pipes and rotate under the parabola connection pipes where the central cooking support pipes are coming out.",
      "description":"You put two 100 mm long pipes of 100 out on the ends of the support and weld them to the 2 pipes coming from the rim on one side and the other two to the other pipe the opposite side. Block the outer support to the cooking support with nuts and bolts so your soup won't be in danger. Nor the whole support from the rim up rotates horizontally, and the parabola rotates around the central support. Done."
    },
    {
      "headline":"The lens legs are 4 bent pipes, the support is a round bended square pipe welded with two lateral round pipes to connect to upper legs, and a central diagonal to hold the pivoting pipe.",
      "description":""
    },
    {
      "headline":"The support has 2 legs detachable with horizontal metal sheets with holes so you can bolt on pivoting wheels, and move the stove as you need.",
      "description":""
    },
    {
      "headline":"If you want to build it, the elevating system is a simple gear anyone can cut with the flex grinder with two lateral welded discs to keep the gear connection of the half parables together alienated, and can be turned with a pipe long one meter with the other end in a L shape.",
      "description":"Easy to make with a flex grinder and a welding machine."
    }
  ],
  "text":" Transportable in a regular station wagon car, or on the rooftop of any car, can be mounted in 15 minutes, and on the cooking support there can be placed any light metal sheet oven of half a meter deep, half a meter wide and half a meter tall, in which can be cooked 3 large pizzas together, or a water boiler of 30 liter (bunch of soup or stew) or a half a meter diameter pan (omelets and fried potatoes for a small army).  Obtain need a sheet of plywood 10 mm thick 3 meters (9.8 ft) long and 1.6 meters (5.2 ft) wide.  Determine on a side the exact center,  Screw in next to the edge a wood screw to it's half,  Take a wire or similar and tie it to the screw, than stretch it to the opposite end of the plywood, and 10 centimeters (3.9 in) before it reaches the edge tie in a pencil.Now you have the compass, rotate the compass to reach the edge where the screw is bolted in, so you draw your parabola form, cut on the curved line with a saw or a powered pendulum saw and separate the 2 wood pieces.  For the outer circle: Glue the straight edge on a piece of wide lumber or plywood to have it stand with the top of the circle up, than you need to make it like a half pipe ditch all along the circular surface, than take iron wire, better if plastic coated, 2 mm thickness, and apply it in the ditch to form it in wire circle arcs., you need some 30 of them.  Draw a 2.4 meters (7.9 ft) circle on the ground, and all around it each 20 centimeters (7.9 in) place a nail to complete the circle, than take wire arches you prepared and put each arch across the center to unite two nails, until you covered all the circle and all the arches are overlapped on top.  Tie the arches together like this: take a wire and close to the top start passing the wire below an arch, above the next to it, below the third one, above the fourth, and so on until you meet the beginning of your wire, and tie them together, than at 5 centimeters (2.0 in) distance outer, tie them again, where the first wire was passing above, pass this one below, and where it was passing below, pass it above. Keep doing that each 5 centimeters (2.0 in) away from each round until the half sphere is completed to the ground. Take away the nails and tie the tips of the arches around the last wire ring.  Take a pipe diameter 80 mm or so, wall thickness 2 mm or more,  cut two pieces of 150 mm each, put them at the end of a 2500 mm long pipe diameter 75 mm and pass them through the sphere in between the last circle at the ground level and the one previous, tie it well with wires that you will connect tying them hard to various knots on the sphere in the area, the pipes must go out of the sphere 100 mm and in the sphere 50 mm, if you can weld them to the wires is better.  Where all the arches overlap, inside the smaller circle tie, cut all the arches in the center than tie them so the smallest circle for good  Take newspapers, large quantity, and acrylic glue (vinyl) for wood, or better oralite (urea) based glue (the additive they put in the asphalt to harden it on the roads) since is waterproof. Soak newspapers in the glue you choose to use without ruining them, than stretch them on the outer side of the parabola, until it's all covered, let it dry a day, than rotate it outside down and do the same inside, repeat outer and inner layers until you have some 10 layers total. reinforce the pipes area well. Allow to dry a few days Check with the wood jugs out and in for perfection, and use car quality putty or fiberglass resin to fill the gaps until the surface is smooth semi-spherical. Impermeable the whole thing by painting it with waterproof paint. Remember the 2 meters (6.6 ft) long pipe you used at point 7 to put in line the pipes in the sphere wall? Cut it in two, and in between the two parts weld a L iron based frame 30 X 30 CM or larger, on which you will place the cooking pot, or the lava stone sheet to grill upon, etc, this is your stove surface. Buy self sticking rolled mirror, cut it in stripes of 2 centimeter (0.8 in) wide, perfectly parallel using a sharp cutter and a metal ruler, starting from the center to the edge put a stripe, than 180 degrees put in continuation a second stripe, than ASIDE put another stripe from edge to edge passing near the center, same on the other side, and so on until the whole sphere is covered, make sure no air bubbles are left. This should do for reflecting a lot of sun. Build the stand you need a rotating plate, teh most common one for free or almost is a rear wheel from any car at the junk yard, take it all, brakes disk and caliper included, it will help you to keep the stove blocked using the old parking brake system. Make a support of 3 regular legs to bolt it beneath and another small support (the center of a rim that fits) to make the upper center to which you weld two pipes of 500 mm diameter 60 mm wall thickness 5 mm with their center on opposite sides and parallel among them. The structure is nothing more than 4 quarter circle arches of 70 mm pipe thin wall (1,5 mm or 2 mm) you stick on the rim welded pipes and rotate under the parabola connection pipes where the central cooking support pipes are coming out. You put two 100 mm long pipes of 100 out on the ends of the support and weld them to the 2 pipes coming from the rim on one side and the other two to the other pipe the opposite side. Block the outer support to the cooking support with nuts and bolts so your soup won't be in danger. Nor the whole support from the rim up rotates horizontally, and the parabola rotates around the central support. Done. The lens legs are 4 bent pipes, the support is a round bended square pipe welded with two lateral round pipes to connect to upper legs, and a central diagonal to hold the pivoting pipe.  The support has 2 legs detachable with horizontal metal sheets with holes so you can bolt on pivoting wheels, and move the stove as you need.  If you want to build it, the elevating system is a simple gear anyone can cut with the flex grinder with two lateral welded discs to keep the gear connection of the half parables together alienated, and can be turned with a pipe long one meter with the other end in a L shape. Easy to make with a flex grinder and a welding machine.",
  "tyn_model":[
    "wire",
    "plywood",
    "compass",
    "nails",
    "wires",
    "newspapers",
    "stove",
    "flex grinder",
    "light metal sheet oven",
    "water boiler",
    "wood screw",
    "pencil",
    "saw",
    "powered pendulum saw",
    "iron wire",
    "wire circle",
    "nail",
    "pipe",
    "acrylic glue",
    "vinyl",
    "glue",
    "wood jugs",
    "waterproof paint",
    "l iron based frame",
    "cooking pot",
    "lava stone",
    "mirror",
    "sharp cutter",
    "metal ruler",
    "rotating plate",
    "parabola connection",
    "nuts and bolts"
  ],
  "tyn_section":[

  ]
}